config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "about", to: "about#index"

  get "up" => "rails/health#show", as: :rails_health_check

  get "sign_up", to: "registrations#new"

  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"

  post "sign_in", to: "sessions#create"

  delete "log_out", to: "sessions#terminate"

  root to: "main#index"

  resources :posts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current <ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true

  after_create :update_user_membership_level

  private

  def update_user_membership_level
    user.calculate_membership_level
  end

  scope :by_user_id, ->(user_id) {
    joins(:user).where(users: { id: user_id })
  }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_secure_password
  validates:email, presence:true

  define_method("calculate_membership_level") do
    membership_levels = {
      "platinum" => 10..Float::INFINITY,
      "gold" => 5..9,
      "silver" => 0..4
    }

    membership_levels.each do |level, range|
      if self.posts.count >= range.begin && self.posts.count <= range.end
        self.update!(membership_level: level)
        break
      end
    end
  end
  private

  def complex_password

    regex = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)[a-zA-Z\d]{8,}\z/

    unless password && regex.match?(password)
     errors.add(:password, "must contain at least one uppercase letter, one lowercase letter, and one digit.")
    end
   end
  end

app/controllers/about_controller.rb
class AboutController < ApplicationController
def index  
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :set_current_user

  def set_current_user
  if session[:user_id]
    Current.user = User.find_by(id: session[:user_id])
  end
 end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Current.user.posts.build
  end

  def create
    @post = Current.user.posts.build(post_params)
    if @post.save
      redirect_to post_path(@post), notice: 'Post was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController <ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Account created successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def user_params
    params.require(:user).permit(:email,:password,:password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController <ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:email])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in successfully"
    else
      flash[:alert] = "Invalid email or password"
      render :new, status: :unprocessable_entity
    end
  end

  def terminate
    session.delete(:user_id)
    redirect_to root_path, notice: "Logged out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>ABCD</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <%= render partial: "shared/navbar" %>
   <div class="container">
    <%= yield %>
   </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1>Welcome</h1>
  <%= link_to 'New Post', new_post_path %>
</div>

app/views/posts/new.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :body %>
  <%= form.text_area :body %>

  <%= form.submit %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about">About</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
          <li class="nav-item">
           <span class="navbar-text"><%= Current.user.email %></span>
          </li> 
          <li class="nav-item">
           <%= button_to "Logout", log_out_path, method: :delete, class: "btn btn-outline-secondary"  %>
          </li>
        <% else %>
          <li class="nav-item">
           <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
          </li>
          <li class="nav-item"> 
           <%= link_to "Login", sign_in_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>